import { NAME } from './constants';

export const FETCH_TRACKS_SUCCESS = `${NAME}/FETCH_TRACKS_SUCCESS`;

export const SET_TRACK = `${NAME}/SET_TRACK`;
export const SET_POPULAR_TRACKS = `${NAME}/SET_POPULAR_TRACKS`;

export const SET_PREV_TRACK = `${NAME}/SET_PREV_TRACK`;
export const SET_CURRENT_TRACK = `${NAME}/SET_CURRENT_TRACK`;
export const SET_NEXT_TRACK = `${NAME}/SET_NEXT_TRACK`;

export const ADD_TO_TRACKLIST = `${NAME}/ADD_TO_TRACKLIST`;
export const REMOVE_FROM_TRACKLIST = `${NAME}/REMOVE_FROM_TRACKLIST`;

export const SET_TRACK_COMMENTS = `${NAME}/SET_TRACK_COMMENTS`;
