import { NAME } from './constants';

export const FETCH_USERS_SUCCESS = `${NAME}/FETCH_USERS_SUCCESS`;
export const SET_USER = `${NAME}/SET_USER`;
export const SET_CURRENT_USER = `${NAME}/SET_CURRENT_USER`;

export const REQUEST_RESOURCE = `${NAME}/REQUEST_RESOURCE`;
export const SET_RESOURCES = `${NAME}/SET_RESOURCES`;
export const SET_RESOURCES_NEXT_PAGE = `${NAME}/SET_RESOURCES_NEXT_PAGE`;

export const SET_RELATED_USERS = `${NAME}/SET_RELATED_USERS`;
