import { NAME } from './constants';

export const FETCH_PLAYLISTS_SUCCESS = `${NAME}/FETCH_PLAYLISTS_SUCCESS`;

export const REQUEST_PLAYLIST_TRACKS = `${NAME}/REQUEST_PLAYLIST_TRACKS`;
export const SET_PLAYLIST_TRACKS = `${NAME}/SET_PLAYLIST_TRACKS`;
export const SET_RELATED_PLAYLISTS = `${NAME}/SET_RELATED_PLAYLISTS`;
